trigger:
- main

variables:
  python.version: '3.9'
  working.directory: 'flask-sklearn'

pool:
  name: Default
  demands:
  - agent.name -equals devops-vm-agent


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    cd ./flask-sklearn
    make all
  displayName: 'make all'

- task: AzureWebApp@1
  inputs:
    appType: 'webAppLinux'
    appName: 'songyang'
    resourceGroupName: 'Azuredevops'
    package: '$(System.DefaultWorkingDirectory)/flask-sklearn'
  displayName: 'deploy to Azure'