name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flask-sklearn

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.x

    - name: Install dependencies
      run: |
        make install

    - name: Lint with pylint
      run: |
        make lint

    - name: Test with pytest
      run: |
        make test
  
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "songyang"
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./flask-sklearn
